name: shegerpay
description: Official Dart/Flutter SDK for the ShegerPay Payment Verification Gateway.
version: 2.2.1
homepage: https://shegerpay.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  crypto: ^3.0.3
